KARENA SOAL NO 2 , SUDAH TERMASUK NO 3 

JADI UNTUK SOAL NO 3 Kita TESTING AJA

# Dari earendil / elwing

ping 10.64.1.2
ping 10.64.1.3
ping 10.64.1.4

UNTUK YANG LAIN SESUAIKAN DENGAN SOAL SEPERTI DARI BARAT KE TIMUR , TIMUR KE BARAT, Dll